services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../:/workspace:cached
      - bundle-cache:/workspace/vendor/bundle
      - $HOME/.ssh/:/home/vscode/.ssh/

    depends_on:
      - db

    env_file:
      - path: ../.env
        required: false

    environment:
      - DATABASE_NAME=guild_manager
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - RAILS_ENV=development
    user: vscode

    command: sleep infinity

    networks:
      - guild-manager-network

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=guild_manager_development
    ports:
      - "5432:5432"
    networks:
      - guild-manager-network

volumes:
  postgres-data:
  bundle-cache:

networks:
  guild-manager-network:
